name: Build LaTeX files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find documents
        run: |
            FILE_NAMES=$(find . -type f -name '*.tex')
            FILE_NAMES="${FILE_NAMES//'%'/'%25'}"
            FILE_NAMES="${FILE_NAMES//$'\n'/'%0A'}"
            FILE_NAMES="${FILE_NAMES//$'\r'/'%0D'}"
            echo "::set-output name=content::$FILE_NAMES"
        id: docs
      - name: Show documents to compile
        run: | 
          echo "documents to compile: ${{ steps.docs.outputs.content }}"
      - name: Compile documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{steps.docs.outputs.content}}
      - name: Upload pdfs
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: ./*.pdf
